version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - SOLR_URL=http://solr:8026/solr/biblio
      - HLB_XML_ENDPOINT=https://apps.lib.umich.edu/browse/categories/xml.php 
      #- HATHIFILE_HOST=hathidb
      #- HATHIFILE_DB=hathifiles
      #- HATHIFILE_USER=root
      #- HATHIFILE_PASSWORD=pass
      #- HATHI_OVERLAP_HOST=hathioverlap
      #- HATHI_OVERLAP_DB=bibliosearch
      #- HATHI_OVERLAP_USER=root
      #- HATHI_OVERLAP_PASSWORD=pass
        #- JRUBY_OPTS=--debug
      - NODB=1
    env_file:
      - .env

  solr:
    image: ghcr.io/mlibrary/library-solr:latest 
    ports:
     - "8026:8026"

  hathidb:
    image: ghcr.io/hathitrust/hathifiles-dev-db:latest

  hathioverlap:
    build: overlap/.

volumes:
  gem_cache:

